@BankingMicroservices.RabbitMQ.Demo.Presentation_HostAddress = http://localhost:5047

GET {{BankingMicroservices.RabbitMQ.Demo.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###
